// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiqynvumcpcrsfmfvufq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pcXludnVtY3BjcnNmbWZ2dWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzAzNjMsImV4cCI6MjA3Mzc0NjM2M30.rRvCBHbo1TzhsRKb3AeuaAoGOuLqeqYFww0i6SccjYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});